name: WoT
markdown: kramdown

# uncomment if in root
#url: "https://w3c.github.com"
#baseurl: "/wot-marketing"
url: "https://www.w3.org"
baseurl: "/WoT"

navigation:
 - title: Groups
   subnavigation:
   - title: Working Group
     url: wg/
   - title: Interest Group
     url: ig/
   - title: Community Groups
     url: cg/
 - title: Activities
   subnavigation:
   - title: Task Forces
     url: activities/task-forces/
   - title: Events
     url: activities/events/
   - title: Web Conference Meetings
     url: activities/meetings/
 - title: Developers
   url: developers/
 - title: Articles
   subnavigation:
   - title: Introduction
     url: articles/introduction
   - title: Press Releases
     url: articles/pressreleases
 - title: Videos
   url: videos/
 - title: Contact
   url: contact/
